### ISSUE TITLE
update fail

### ISSUE THREAD

**Issue by xxfenxx** [adow/SecrecySwift#1]
The following build commands failed:
    CompileSwift normal arm64 /Users/hanzimacbook-pro/Desktop/XSWAPP/Carthage/Checkouts/SecrecySwift/SecrecySwift/SecrecyExtension.swift
    CompileSwift normal arm64 /Users/hanzimacbook-pro/Desktop/XSWAPP/Carthage/Checkouts/SecrecySwift/SecrecySwift/HMAC.swift
    CompileSwift normal arm64 /Users/hanzimacbook-pro/Desktop/XSWAPP/Carthage/Checkouts/SecrecySwift/SecrecySwift/RSA.swift
    CompileSwift normal arm64 /Users/hanzimacbook-pro/Desktop/XSWAPP/Carthage/Checkouts/SecrecySwift/SecrecySwift/AES.swift
    CompileSwiftSources normal arm64 com.apple.xcode.tools.swift.compiler
(5 failures)

**Comment by adow** [comment]
Compile failed in `Carthage Update`?
