### ISSUE TITLE
可以兼容OSX吗？

### ISSUE THREAD

**Issue by Dalodd** [adow/SecrecySwift#2]
您好~可以写一个兼容 OS X 的版本吗？

**Comment by adow** [comment]
不好意思，我没写过 OSX 相关的开发，所以不是很清楚该怎么弄，我想直接把代码文件直接放到项目里面应该是可行的，可以参考下手工部署的说明。

**Comment by Dalodd** [comment]
因为框架略有不同，所以要修改一部分实现的。。
非常感谢~
