### ISSUE TITLE
用aes加密时，位数低于8位为什么会报错呀？

### ISSUE THREAD

**Issue by CoderTanX** [adow/SecrecySwift#6]
ileprivate func test_aes(){
        let key = "0000000000000000"
        let raw = "012345"
//        let raw = "012345678"
//        let raw = "123你好把呵呵"
//        let raw = "你好!a"
        let encrypt_1 = raw.aesEBCEncrypt(key)
        print("aes encrypt hexString:\(encrypt_1!.hexString)")

**Comment by adow** [comment]
是的，只要 raw 长度低于8位， CommonCrypto 中 CCCrypto 就返回 -4301 了，我也不知道为什么，也搜不到原因。

**Comment by adow** [comment]
找到原因了，因为 raw 低于8位的时候，创建的输出的缓冲区太小导致的（输出的缓冲区大小是依据输入的大小来创建的）
